# Generated by Django 2.0 on 2017-12-20 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stems', '0002_auto_20171220_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualitynews',
            name='location',
            field=models.TextField(null=True),
        ),
    ]
